namespace: dtlandscape-dvl
lifecycle: dvl

openshift_cluster_content:
- object: builds
  content:
  - name: "deploy build pipeline to dev"
    template: "{{ inventory_dir }}/../../.openshift/templates/deploy.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/deploy-{{ lifecycle }}"
    params_from_vars:
      NAMESPACE: "{{ namespace }}" 
# - object: route
#   content:
#   - name: "create route"
#     template: "{{ inventory_dir }}/../../.openshift/templates/route.yml"
#     params: "{{ inventory_dir }}/../../.openshift/params/route-{{ lifecycle }}"
#     params_from_vars:
#       NAMESPACE: "{{ namespace }}"

